- name: Configure SSH and sudo settings
  hosts: servers
  become: yes
  
  tasks:
    - name: Copy SSH public key
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Update SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
        - { regexp: '^UsePAM', line: 'UsePAM no' }
      notify: restart sshd

    - name: Set up passwordless sudo
      lineinfile:
        path: /etc/sudoers
        regexp: '^{{ ansible_user }}'
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted