- name: Initial SSH key deployment
  hosts: servers
  gather_facts: false # Skip fact gathering for speed
  vars_prompt:
    - name: ansible_password
      prompt: "Enter SSH password for servers"
      private: true

  tasks:
    - name: Wait for SSH connection
      wait_for_connection:
        timeout: 10

    - name: Gather facts after connection
      setup:

    - name: Ensure .ssh directory exists
      file:
        path: "~/.ssh"
        state: directory
        mode: "0700"
      become: true

    - name: Deploy SSH keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
      become: true

    - name: Update SSH configuration to disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - {
            regexp: "^PasswordAuthentication",
            line: "PasswordAuthentication no",
          }
        - {
            regexp: "^ChallengeResponseAuthentication",
            line: "ChallengeResponseAuthentication no",
          }
        - { regexp: "^UsePAM", line: "UsePAM no" } # Keep PAM enabled for system authentication
      become: true

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
      become: true
