- name: Reboot servers if required
  hosts: servers
  become: true

  tasks:
    - name: Reboot server
      reboot:
        msg: "Rebooting due to system updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
