---
- name: Configure SSH Security
  hosts: all
  become: true
  vars:
    ssh_public_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIKm8Whiz7KcGzArrMB9NPHyUsLckYv+jCVcLxPObJvk"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOFhTNajU8kAGnJD8GWMsvM9GmU5iKmG375upAkhs0se"

  tasks:
    # First ensure SSH keys are in place before disabling password auth
    - name: Set up SSH directories
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: "0700"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add public keys to user authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ item }}"
      with_items: "{{ ssh_public_keys }}"

    # Configure sshd with best practices
    - name: Update SSH configuration
      blockinfile:
        path: /etc/ssh/sshd_config
        backup: yes
        block: |
          PasswordAuthentication no
          ChallengeResponseAuthentication no
          PubkeyAuthentication yes
          PermitRootLogin no
          UsePAM yes
          X11Forwarding no
          PrintMotd no

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
